### PR TITLE
Fix "league/commonmark" version in "composer.json"

### PR DESCRIPTION
**Pull request by henriquemoody**

### CODE REVIEW

**Comment by henriquemoody** [comment]
@mnapoli, this should fix the tests for a while. Can you enable Travis and Scrutinizer for this project and also allow to open issues?

**Comment by mnapoli** [comment]
Done!

**Comment by henriquemoody** [comment]
Thanks! Looks like Travis is a little lazy today. I just sent #3 and no response, can you give a check?

**Comment by mnapoli** [comment]
-_- I enabled travis on mnapoli/markua, not couscousphp/markua :p

Fixed that!

**Comment by henriquemoody** [comment]
it's happens :stuck_out_tongue_closed_eyes:

**Pull request merged**
